server:
  port: 8081

management:
  endpoint:
    health:
      show-details=always

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/nakupovalko
          jwk-set-uri: http://localhost:8080/realms/nakupovalko/protocol/openid-connect/certs
        client:
          registration:
            keycloak:
              client-id: nakupovalko-prijava-client
              client-secret: IxNZ2hu64wm6remozqLHPH2AKByaFU9K
              authorization-grant-type: authorization_code
              scope: openid, profile, email #to use OIDC, you must always request at least the openid scope.
          provider:
            keycloak:
              issuer-uri: http://localhost:8080/

              #Redirect to keycloak login, after login user is redirected using redirectURI
              #http://localhost:8080/realms/nakupovalko/protocol/openid-connect/auth?scope=openid&response_type=code&client_id=nakupovalko-prijava-client&redirect_uri=https://www.google.com
