apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-mysql
  namespace: nakupovalko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-mysql
  template:
    metadata:
      labels:
        app: item-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mysql
            - name: MYSQL_DATABASE
              value: itemdb
