apiVersion: v1
kind: Service
metadata:
  name: item-mysql
  namespace: nakupovalko
spec:
  selector:
    app: item-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
#  type: LoadBalancer
