apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nakupovalko-ingress
  namespace: nakupovalko
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cert-manager-webhook-duckdns-production #cert-manager-webhook-duckdns-staging
    acme.cert-manager.io/http01-ingress-class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    #- host: nakupovalko.duckdns.org
    - http:
        paths:
          # Keycloak
          - path: /realms/nakupovalko/protocol/openid-connect/token
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080

          #- path: /realms/nakupovalko/protocol/openid-connect/auth?scope=openid&response_type=code&client_id=nakupovalko-prijava-client&redirect_uri=https:/nakupovalko.duckdns.org/home"
          - path: /realms/nakupovalko/protocol/openid-connect/auth
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080


          # Prijava
          - path: /nakupovalko-login
            pathType: Prefix
            backend:
              service:
                name: prijava-service
                port:
                  number: 8081
          - path: /home
            pathType: Prefix
            backend:
              service:
                name: prijava-service
                port:
                  number: 8081
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: prijava-service
                port:
                  number: 8081

          - path: /api/user-info
            pathType: Prefix
            backend:
              service:
                name: prijava-service
                port:
                  number: 8081

          - path: /api/set-token
            pathType: Prefix
            backend:
              service:
                name: prijava-service
                port:
                  number: 8081

          - path: /api/logged-in-user
            pathType: Prefix
            backend:
              service:
                name: prijava-service
                port:
                  number: 8081

          - path: /api/protected
            pathType: Prefix
            backend:
              service:
                name: prijava-service
                port:
                  number: 8081


          - path: /users
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 8082

          - path: /profile
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 8082


  tls:
    - hosts:
        - 52.143.5.236
      secretName: ingress-tls