apiVersion: apps/v1
kind: Deployment
metadata:
  name: prijava-service
  labels:
    app: prijava-service
  namespace: nakupovalko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nakupovalko-exposer #so its on the same external ip
  template:
    metadata:
      labels:
        app: nakupovalko-exposer
    spec:
      containers:
        - name: prijava-service
          image: vm0012/nakupovalko-prijava:2.0.0
          ports:
            - containerPort: 8081
          env:
            - name: KEYCLOAK_ISSUER_URI
              value: "http://20.61.156.48:8080/realms/nakupovalko"
---
apiVersion: v1
kind: Service
metadata:
  name: prijava-service
  namespace: nakupovalko
spec:
  selector:
    app: prijava-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
