apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
  namespace: nakupovalko
type: Opaque
stringData:
  azurestorageaccountname: nakupovalkokeycloak
  azurestorageaccountkey: o7Wax5mXuFoEVp437Fmp6KzJlZn4tdpWehtPtbtQTuKgVC5WeYdsTHnY5Xi4jsVQ34viBC/j0Jou+AStaCG+sw==
