apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: item-service
  template:
    metadata:
      labels:
        app: item-service
    spec:
      containers:
        - name: item-service
          image: item-item-service:latest  # Replace with your Docker image
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/itemdb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: mysql
            - name: MANAGEMENT.ENDPOINTS.WEB.EXPOSURE.INCLUDE
              value: prometheus
