apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-grafana
  namespace: nakupovalko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-grafana
  template:
    metadata:
      labels:
        app: item-grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000
