apiVersion: v1
kind: Service
metadata:
  name: item-grafana
  namespace: nakupovalko
spec:
  selector:
    app: item-grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
