apiVersion: v1
kind: ConfigMap
metadata:
  name: item-prometheus-config
  namespace: nakupovalko
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: "item-service"
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["item-service:8089"]
