apiVersion: v1
kind: Service
metadata:
  name: item-prometheus
  namespace: nakupovalko
spec:
  selector:
    app: item-prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
