server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/nakupovalko
          jwk-set-uri: http://keycloak:8080/realms/nakupovalko/protocol/openid-connect/certs
        client:
          registration:
            keycloak:
              client-id: nakupovalko-prijava-client
              client-secret: 9so9VdJZJXQnH8pBzfXSGZivWY2Bq5ZY #IxNZ2hu64wm6remozqLHPH2AKByaFU9K
              authorization-grant-type: authorization_code
              scope: openid, profile, email #to use OIDC, you must always request at least the openid scope.
          provider:
            keycloak:
              issuer-uri: http://localhost:8080/

              #Redirect to keycloak login, after login user is redirected using redirectURI
              #http://localhost:8080/realms/nakupovalko/protocol/openid-connect/auth?scope=openid&response_type=code&client_id=nakupovalko-prijava-client&redirect_uri=https://www.google.com

resilience4j:
  retry:
    instances:
      getUserInfo:
        max-attempts: 3
        wait-duration:
          seconds: 2


#elk
logging:
  level:
    org.springframework: INFO
    si.fri.skupina06: DEBUG
  file:
    path: .
    name: login-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

