apiVersion: v1
kind: Service
metadata:
  name: shoppinglist-mysql
  namespace: nakupovalko
spec:
  selector:
    app: shoppinglist-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
#  type: LoadBalancer
