apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shoppinglist-ingress
  namespace: nakupovalko
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/shopping-lists
            pathType: Prefix
            backend:
              service:
                name: shoppinglist
                port:
                  number: 8090
