apiVersion: v1
kind: Service
metadata:
  name: shoppinglist-service
spec:
  selector:
    app: shoppinglist-service
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: ClusterIP