#version: '3.8'
services:
  item-service:
    build:
      context: .
    ports:
      - "8089:8089"
    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/itemdb
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/itemdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
      MANAGEMENT.ENDPOINTS.WEB.EXPOSURE.INCLUDE: prometheus
      MANAGEMENT.METRICS.EXPORT.PROMETHEUS.ENABLED: true
      SPRINGDOC.API-DOCS.PATH: /v3/api-docs
    depends_on:
#      - mysql
      - prometheus
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: itemdb
    ports:
      - "3307:3306"
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
