apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
  namespace: nakupovalko
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS user (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        surname VARCHAR(100) NOT NULL,
        username VARCHAR(100) NOT NULL,
        email VARCHAR(100) UNIQUE NOT NULL
        );

    INSERT IGNORE INTO user (name, surname, username, email)
    VALUES 
        ('Anze', 'Hočevar', 'anzeh', 'anze.hocevar@gmail.com'),
        ('Veronika', 'Matek', 'vm0012', 'vm0012@student.uni-lj.si'),
        ('Micka', 'Novak', 'user', 'micka.novak@hotmail.si');


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: nakupovalko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpass
            - name: MYSQL_DATABASE
              value: userdb
            - name: MYSQL_USER
              value: myuser
            - name: MYSQL_PASSWORD
              value: mypass

          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5
            successThreshold: 1

          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: mysql-data
          emptyDir: {}
        - name: mysql-init
          configMap:
            name: mysql-init

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: nakupovalko
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
