apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: nakupovalko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: nakupovalko
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "user-service"
        static_configs:
          - targets: ["user-service.nakupovalko.svc.cluster.local:8082"]

      - job_name: "elasticsearch"
        static_configs:
          - targets: ["elasticsearch.nakupovalko.svc.cluster.local:9200"]

      - job_name: "logstash"
        static_configs:
          - targets: ["logstash.nakupovalko.svc.cluster.local:5044"]
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: nakupovalko
spec:
  ports:
    - port: 9090
  selector:
    app: prometheus
