apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: nakupovalko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: vm0012/nakupovalko-user:1.0.0
          ports:
            - containerPort: 8082

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 30

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: nakupovalko
spec:
  #type: LoadBalancer
  ports:
    - port: 8082
  selector:
    app: user-service
