services:
  mysql:
    container_name: mysql_shopping_list
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: shopping_list_db
    ports:
      - "3308:3306" # host : container
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app

  shopping-list-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shopping_list_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
#      SPRING_APPLICATION_NAME: ShoppingList
#      MANAGEMENT.ENDPOINTS.WEB.EXPOSURE.INCLUDE: prometheus
#      MANAGEMENT.METRICS.EXPORT.PROMETHEUS.ENABLED: true
#      SPRINGDOC.API-DOCS.PATH: /v3/api-docs
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app
    restart: on-failure


volumes:
  mysql_data:

#  prometheus:
#    image: prom/prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    networks:
#      - app
#
#  grafana:
#    image: grafana/grafana
#    ports:
#      - "3000:3000"
#    networks:
#      - app

networks:
  app:
